name: PHPUnit Testing

on:
  push:
    branches:
      - master

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Composer Dependencies
        run: composer install

      - name: Run PHPUnit Tests
        run: phpunit
        working-directory: ./wp-content/themes/twentytwentyone-child
