name: PHPUnit Testing

on:
  push:
    branches:
      - master

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: SandeepGhoshYudiz/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies
        run: composer install

      - name: Set up WordPress
        run: bash bin/install-wp-tests.sh wordpress_test root root localhost $WP_VERSION

      - name: Run PHPUnit Tests
        run: phpunit
